### ISSUE TITLE
Make ips

### ISSUE THREAD

**Issue by khatatbih** [pulp-platform/bigpulp#12]
need help to solve this issue
UBUNTU 18.04 LTS
make ips
cd ips/xilinx_axi_xbar_rab_cfg; make clean all
make[1]: Entering directory '/home/user/Desktop/hero/bigpulp/fpga/ips/xilinx_axi_xbar_rab_cfg'
rm -rf ip/*
mkdir -p ip
rm -rf xilinx_axi_xbar_rab_cfg.*
rm -rf component.xml
rm -rf vivado*.jou
rm -rf vivado*.log
rm -rf vivado*.str
rm -rf xgui
rm -rf .Xil
vivado -mode batch -source tcl/run.tcl
make[1]: vivado: Command not found
Makefile:4: recipe for target 'all' failed
make[1]: *** [all] Error 127
make[1]: Leaving directory '/home/user/Desktop/hero/bigpulp/fpga/ips/xilinx_axi_xbar_rab_cfg'
Makefile:4: recipe for target 'rab' failed
make: *** [rab] Error 2

**Comment by andreaskurth** [comment]
`make[1]: vivado: Command not found`

Vivado 2017.2 needs to be installed and invokable as `vivado`.

**Comment by khatatbih** [comment]
Dear  Andreas,
I installed Vivado lab 2017.2, but the same problem, I can invoked it to
the simulator
Thank

**Comment by andreaskurth** [comment]
You closed the issue; does that mean you have solved it? If so, please let us know.

If you have Vivado installed but cannot invoke it, it is likely not on your `PATH`. Please execute `echo $PATH` and make certain the `bin` directory (which contains the `vivado` executable) of your Vivado 2017.2 installation is in there. If you believe `PATH` is correctly set but you still cannot invoke `vivado`, please post the output of running `echo $PATH` and `ls -l $VIVADO_INSTALL_DIR/bin`, where `$VIVADO_INSTALL_DIR` is the path to your Vivado 2017.2 installation.

**Comment by khatatbih** [comment]
Dear Anderas,

I installed vivado but  when make ips I get the following error message any
help I will appreciate that.

Thank you

 make ips
cd ips/xilinx_axi_xbar_rab_cfg; make clean all
make[1]: Entering directory
'/home/khatatbih/Desktop/hero/bigpulp/fpga/ips/xilinx_axi_xbar_rab_cfg'
rm -rf ip/*
mkdir -p ip
rm -rf xilinx_axi_xbar_rab_cfg.*
rm -rf component.xml
rm -rf vivado*.jou
rm -rf vivado*.log
rm -rf vivado*.str
rm -rf xgui
rm -rf .Xil
vivado -mode batch -source tcl/run.tcl
make[1]: vivado: Command not found
Makefile:4: recipe for target 'all' failed
make[1]: *** [all] Error 127
make[1]: Leaving directory
'/home/khatatbih/Desktop/hero/bigpulp/fpga/ips/xilinx_axi_xbar_rab_cfg'
Makefile:4: recipe for target 'rab' failed
make: *** [rab] Error 2

**Comment by andreaskurth** [comment]
Please post the console output of `echo $PATH` and of `ls -l $VIVADO_INSTALL_DIR/bin`, where `$VIVADO_INSTALL_DIR` is the directory you installed Vivado 2017.2 in.

**Comment by khatatbih** [comment]
Hi
The console output  of  echo $PATH and of ls -l $VIVADO_INSTALL_DIR/bin is

```
khatatbih@ubuntu:~/Desktop/vivado/Vivado/2017.2$ cd bin
khatatbih@ubuntu:~/Desktop/vivado/Vivado/2017.2/bin$  echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
khatatbih@ubuntu:~/Desktop/vivado/Vivado/2017.2/bin$ ls -l
total 144
-rwxr-xr-x 1 root root  3868 Jun 15  2017 hw_server
-rwxr-xr-x 1 root root   917 Jun 15  2017 hw_serverpv
-rwxr-xr-x 1 root root 13886 Jun 15  2017 loader
-rw-r--r-- 1 root root  5404 Jun 15  2017 rdiArgs.sh
-rwxr-xr-x 1 root root  3120 Jun 15  2017 sdx_server
-rwxr-xr-x 1 root root  6591 Jun 15  2017 setupEnv.sh
-rwxr-xr-x 1 root root  1093 Jun 15  2017 svf_utility
-rwxr-xr-x 1 root root   917 Jun 15  2017 symbol_server
-rwxr-xr-x 1 root root 18354 Jun 15  2017 sysgen
-rwxr-xr-x 1 root root   917 Jun 15  2017 tcflog
drwxr-xr-x 3 root root  4096 Feb 27 13:36 unwrapped
-rwxr-xr-x 1 root root  1024 Jun 15  2017 updatemem
-rwxr-xr-x 1 root root   884 Jun 15  2017 vcse_server
-rwxr-xr-x 1 root root   914 Jun 15  2017 vivado
-rwxr-xr-x 1 root root  1121 Jun 15  2017 vlm
-rwxr-xr-x 1 root root   873 Jun 15  2017 wbtcv
-rwxr-xr-x 1 root root   770 Jun 15  2017 xar
-rwxr-xr-x 1 root root   770 Jun 15  2017 xelab
-rwxr-xr-x 1 root root   851 Jun 15  2017 xlicclientmgr
-rwxr-xr-x 1 root root   851 Jun 15  2017 xlicsrvrmgr
-rwxr-xr-x 1 root root   850 Jun 15  2017 xlictsinit
-rwxr-xr-x 1 root root   770 Jun 15  2017 xsc
-rwxr-xr-x 1 root root  1633 Jun 15  2017 xsdb
-rwxr-xr-x 1 root root   770 Jun 15  2017 xsim
-rw-r--r-- 1 root root   917 Jun 15  2017 xvc_pcie
-rwxr-xr-x 1 root root   770 Jun 15  2017 xvhdl
-rwxr-xr-x 1 root root   770 Jun 15  2017 xvlog
khatatbih@ubuntu:~/Desktop/vivado/Vivado/2017.2/bin$ 
```

**Comment by andreaskurth** [comment]
The output of `echo $PATH` shows that Vivado's `bin` directory is not on your `PATH`. Please add it by executing `export PATH=$HOME/Desktop/vivado/Vivado/2017.2/bin:$PATH` at the start of every shell session in which you need to invoke Vivado through the `vivado` command.

**Comment by khatatbih** [comment]
Hi
I get this error , if you can help me with that.
Thank you

./compile_kernel.sh -j8
ERROR: Missing required environment variables KERNEL_ARCH and/or
KERNEL_CROSS_COMPILE, aborting now.

**Comment by andreaskurth** [comment]
So I guess this problem is resolved? Let's close this issue in that case.

The problem you are describing now concerns the [HERO SDK](https://github.com/pulp-platform/hero-sdk). You need to `source scripts/hero-z-7045-env.sh` to get those environment variables defined. If you have further problems with the HERO SDK, please open an issue there.

**Comment by khatatbih** [comment]
When Execute this command I received the following error at the end in Vivado

cd bigpulp-z-70xx
make clean gui

mkdir: cannot create directory ‘/Home’: Permission denied
    while executing
"exec mkdir -p $SDK_WORKSPACE/"
    invoked from within
"if [info exists ::env(SDK_WORKSPACE)] {
    exec mkdir -p $SDK_WORKSPACE/
    write_hwdef -force -file $SDK_WORKSPACE/bigpulp-z-70xx.hdf
} else {
    ..."
    (file "tcl/run.tcl" line 208)
