### ISSUE TITLE
Support Vivado 2018.2

### ISSUE THREAD

**Issue by eejlny** [pulp-platform/bigpulp#7]
Hello, 

I tried the zedboard configuration and run into problems but since it is not officially supported I tried the zc706.  Things go well until I get to the final step of trying to get the bit file with

.../bigpulp/fpga/bigpulp-z-70xx$ make clean gui

There when Vivado opens the project I am getting errors like:

[axi_bram_cntlr-1] Port-A interface property <CONFIG.READ_WRITE_MODE> is not defined.

![image](https://user-images.githubusercontent.com/34302344/48347744-0d186780-e677-11e8-823b-6b78f340c714.png)

I am using Vivado 2018.2. I wonder if you have been able to check this ?

Thanks,

**Comment by andreaskurth** [comment]
Hi eejlny,

Thanks for your report. bigpulp currently requires Vivado 2017.2 (with legacy support for 2016.3, 2016.1, and 2015.1), but we want to support a 2018 variant, so 2018.2 is a candidate.

I have created the `vivado-2018.2` branch, which should fix the problem you reported. On that branch, block diagram generation works fine for me, and implementation is currently running. I will test the implementation on a board within the next few days and possibly fix more problems, but feel free to try the branch already.

Best,
Andreas

**Comment by andreaskurth** [comment]
Vivado 2018.3 is now supported (#13), 2018.2 will not be.
